version: "3.9"
services:
  db:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=passw0rd
      - MONGO_INITDB_DATABASE=computershop
    ports:
      - 27017:27017
    volumes:
      - ./_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: passw0rd
      ME_CONFIG_MONGODB_URL: mongodb://root:passw0rd@db:27017/
  webapi:
    image: sing3demons/combuy:0.1.2
    # image: sing3demons/combuy:0.1
    container_name: combuy
    ports:
     - 3000:3000
    environment:
    - PORT=3000
    - NODE_ENV=development
    - MONGODB_URI=mongodb://root:passw0rd@db:27017/
    - DOMAIN=http://localhost:3000
    - JWT_SECRET=jwt_secret_test_mode
    - PAY_STRIPE=secret_test_mode
    - SECRET_KEY=secret_test_mode
    - API_KEY_MAIL=secret_test_mode
    restart: always
    depends_on:
     - db
    links:
      - "db:db"