version: "3.9"
services:
  db:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=computershop
    ports:
      - 27017:27017
    volumes:
      - ./_mongo_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URI}
  webapi:
    image: sing3demons/combuy:0.1
    container_name: combuy
    ports:
     - 3000:3000
    environment:
    - PORT=3000
    - NODE_ENV=development
    - MONGODB_URI=${MONGODB_URI}
    - DOMAIN=http://localhost:3000
    - JWT_SECRET=${JWT_SECRET}
    - PAY_STRIPE=${PAY_STRIPE}
    - SECRET_KEY=${SECRET_KEY}
    - API_KEY_MAIL=${API_KEY_MAIL}
    restart: always
    depends_on:
     - db
    links:
      - "db:db"