apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: combuy-pvc
  namespace: combuy
  labels:
    app: combuy
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany